c*****************************************************************
c	$RCSfile: outval.inc,v $
c	$Revision: 1.1 $
c	$Date: 2006/10/13 18:25:50 $
c	$Locker: wellsj $
c	
c$Log: outval.inc,v $
cRevision 1.1  2006/10/13 18:25:50  wellsj
cInitial revision
c
cRevision 1.2  2003/11/24 15:39:06  conklind
cAdd symbols for determining length at compile time.
c
cRevision 1.1  2003/11/19 23:47:00  conklind
cInitial revision
c
c******************************************************************
      common/plot1/vals1(281)
      common/plot2/vals2(108)
      common/plot3/vals3(112)
      common/plot4/vals4(15)
      real vals1, vals2, vals3, vals4
