        
c*****************************************************************
c	$RCSfile: pi.inc,v $
c	$Revision: 1.1 $
c	$Date: 2006/10/13 18:25:50 $
c	$Locker: wellsj $
c	
c$Log: pi.inc,v $
cRevision 1.1  2006/10/13 18:25:50  wellsj
cInitial revision
c
cRevision 1.2  2004/09/25 00:14:20  bachelet
cheader
c
c******************************************************************
	real PEEDEE, PI, PI2
	parameter (PEEDEE=0.0112372)
	parameter (PI=3.141592653589793)
	parameter (PI2=6.283185307179586)
